In [26]:
!pwd

/gpfs/bbp.cscs.ch/project/proj34/metabolismndam/analysis/sim_analyze

In [ ]:
import efel

from bluepy.v2 import Simulation

from bluepy.v2 import Circuit
from bluepy.v2 import Cell
from bluepy.v2.enums import Synapse

from os import path

import pandas as pd

import numpy as np

from matplotlib import pyplot as plt
import seaborn as sns

import h5py

import pickle

In [2]:
sim_f = '/gpfs/bbp.cscs.ch/project/proj34/sh_ngvm/column/ina_test/BlueConfig'

sim = Simulation(sim_f)

Have keys ({'FlushBufferScalar'}) that are not defined for section: Run

In [3]:
#Report NaCurrCellSum
#    Target L5mc2MCTPCA
#    Type Summation

report = sim.report('NaCurrCellSum', source='h5') # NaCurrCellSum
NaCurrCellSum = report.get()
print("NUMBER OF COLUMNS:",len(NaCurrCellSum.columns))

Ignoring unknown key: 'FlushBufferScalar'

NUMBER OF COLUMNS: 2132

In [4]:
#Report NaCurrSoma
#    Target L5mc2MCTPCA
#    Type compartment
    
report = sim.report('NaCurrSoma', source='h5') # NaCurrentAllCmps
NaCurrSoma = report.get()
print("NUMBER OF COLUMNS:",len(NaCurrSoma.columns))

Ignoring unknown key: 'FlushBufferScalar'

NUMBER OF COLUMNS: 2132

In [5]:
#Report NaCurrCompSum
#    Target AllComps_l5s1
#    Type Summation


report = sim.report('NaCurrCompSum', source='h5')
NaCurrCompSum = report.get()
print("NUMBER OF COLUMNS:",len(NaCurrCompSum.columns))

Ignoring unknown key: 'FlushBufferScalar'

NUMBER OF COLUMNS: 1561041

In [6]:
# from iter seg in py
param = pd.read_csv('/gpfs/bbp.cscs.ch/project/proj34/sh_ngvm/column/ina_test/param_2020121609.txt',sep='\t',header=None)

param.columns = ['c_gid','rank','idxm','current_ina_nA','current_ina_origin_noScaling','nais_mean']
param['c_gid'] = param['c_gid'].astype(int)
param['idxm'] = param['idxm'].astype(float)

In [7]:
param.head()

    c_gid  rank  idxm  current_ina_nA  current_ina_origin_noScaling  nais_mean
0  153875   851   0.0   -3.944791e-14                     -0.153593       10.0
1  153780   843   0.0   -4.078456e-14                     -0.155701       10.0
2  153891   852   0.0   -3.057425e-14                     -0.160558       10.0
3  153927   855   0.0   -3.245417e-14                     -0.168677       10.0
4  153761   839   0.0   -4.230404e-14                     -0.196595       10.0

In [8]:
# check that all mpi ranks output data
len(param['rank'].unique())

1024

In [9]:
current_ina_nA = param.pivot(index='idxm', columns='c_gid', values='current_ina_nA')

In [10]:
current_ina_origin_noScaling = param.pivot(index='idxm', columns='c_gid', values='current_ina_origin_noScaling')

In [11]:
current_ina_nA.head()

c_gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
idxm,,,,,,,,,,,,,,,,,,,,,
0.0,-2.356995e-14,-3.621153e-14,-3.811826e-14,-4.713965e-14,-3.019494e-14,-3.505685e-14,-2.543569e-14,-3.847259e-14,-3.125212e-14,-2.897759e-14,...,-1.246892e-14,-3.775368e-14,-1.070329e-13,-4.072557e-14,-4.089569e-14,-3.146717e-14,-5.642699e-12,-7.166694e-14,-1.495253e-14,-3.559975e-14
1.0,-2.415063e-14,-3.741499e-14,-3.911523e-14,-4.796442e-14,-3.062866e-14,-3.648805e-14,-2.668025e-14,-3.900738e-14,-3.346913e-14,-2.935617e-14,...,-1.248229e-14,-4.097909e-14,-1.055954e-11,-6.565445e-14,-6.620055e-14,-3.296984e-14,-4.166243e-13,-1.667430e-11,-1.485439e-14,-3.654118e-14
2.0,-2.445118e-14,-3.792882e-14,-3.952248e-14,-4.805878e-14,-3.037458e-14,-3.705799e-14,-2.733753e-14,-3.906662e-14,-3.447536e-14,-2.934538e-14,...,-1.248964e-14,-4.189792e-14,-7.119499e-17,-8.128112e-12,-8.109960e-12,-3.168154e-14,-1.078784e-16,-5.962185e-14,-1.450602e-14,-3.667431e-14
3.0,-2.456489e-14,-3.820249e-14,-3.959483e-14,-4.788861e-14,-3.013717e-14,-3.730249e-14,-2.735418e-14,-3.877036e-14,-3.481065e-14,-2.922336e-14,...,-1.241973e-14,-4.228393e-14,-4.423731e-17,-6.132219e-13,-5.928999e-13,-2.445020e-14,-1.011859e-16,-3.106414e-16,-1.396558e-14,-3.662658e-14
4.0,-2.458771e-14,-3.849216e-14,-3.951426e-14,-4.753230e-14,-2.989289e-14,-3.748175e-14,-2.636555e-14,-3.843134e-14,-3.447885e-14,-2.900486e-14,...,-1.237078e-14,-4.269587e-14,-5.974833e-17,-1.145919e-14,-1.125613e-14,-1.904399e-14,-1.457575e-16,-3.371082e-16,-1.348743e-14,-3.607089e-14

In [12]:
current_ina_origin_noScaling.head()

c_gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
idxm,,,,,,,,,,,,,,,,,,,,,
0.0,-0.160468,-0.159459,-0.160119,-0.149955,-0.149311,-0.154695,-0.161719,-0.147015,-0.159177,-0.155417,...,-0.198837,-0.484355,-1.846408,-0.460048,-0.462009,-0.350510,-79.946602,-0.807793,-0.172195,-0.321119
1.0,-0.164471,-0.164821,-0.164332,-0.152594,-0.151452,-0.161078,-0.169763,-0.149077,-0.170439,-0.157475,...,-0.198966,-0.528896,-43.351501,-0.747137,-0.753510,-0.367944,-5.643083,-93.875719,-0.171086,-0.329685
2.0,-0.166572,-0.167122,-0.166058,-0.152902,-0.150195,-0.163628,-0.174058,-0.149314,-0.175551,-0.157436,...,-0.199011,-0.540873,-0.001053,-89.918351,-89.802987,-0.353590,-0.001570,-0.413588,-0.167088,-0.330727
3.0,-0.167378,-0.168341,-0.166369,-0.152366,-0.149022,-0.164724,-0.174249,-0.148186,-0.177252,-0.156790,...,-0.197865,-0.545092,-0.000651,-5.364713,-5.205487,-0.270395,-0.001479,-0.003359,-0.160823,-0.330153
4.0,-0.167553,-0.169633,-0.166036,-0.151236,-0.147815,-0.165526,-0.167879,-0.146894,-0.175565,-0.155615,...,-0.197044,-0.550130,-0.000889,-0.128128,-0.125786,-0.209181,-0.002172,-0.003576,-0.155307,-0.324878

In [14]:
NaCurrCellSum.head()

gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
time,,,,,,,,,,,,,,,,,,,,,
0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1.0,-0.023570,-0.036212,-0.038118,-0.047140,-0.030195,-0.035057,-0.025436,-0.038473,-0.031252,-0.028977,...,-0.012469,-0.037754,-0.107033,-0.040726,-0.040896,-0.031467,-5.642692,-0.071667,-0.014953,-0.035600
2.0,-0.023570,-0.036212,-0.038118,-0.047140,-0.030195,-0.035057,-0.025436,-0.038473,-0.031252,-0.028977,...,-0.012469,-0.037754,-0.107033,-0.040726,-0.040896,-0.031467,-5.642692,-0.071667,-0.014953,-0.035600
3.0,-0.024151,-0.037415,-0.039115,-0.047964,-0.030629,-0.036488,-0.026680,-0.039007,-0.033469,-0.029356,...,-0.012482,-0.040979,-10.559533,-0.065654,-0.066201,-0.032970,-0.416624,-16.674309,-0.014854,-0.036541
4.0,-0.024451,-0.037929,-0.039522,-0.048059,-0.030375,-0.037058,-0.027338,-0.039067,-0.034475,-0.029345,...,-0.012490,-0.041898,-0.000071,-8.128112,-8.109953,-0.031682,-0.000108,-0.059622,-0.014506,-0.036674

In [13]:
NaCurrSoma.head()

gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
time,,,,,,,,,,,,,,,,,,,,,
0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1.0,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,...,-8.248523e-07,-8.751574e-07,-1.052132e-06,-1.270941e-07,-1.274838e-07,-1.252790e-07,-2.036757e-06,-1.016562e-06,-1.686080e-08,-1.260644e-07
2.0,-0.000004,-0.000005,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000004,-0.000005,-0.000004,...,-8.318569e-07,-9.124710e-07,-9.146413e-01,-1.507225e-07,-1.507437e-07,-1.314746e-07,-3.838708e-03,-8.919586e-01,-1.671544e-08,-1.307304e-07
3.0,-0.000004,-0.000005,-0.000004,-0.000004,-0.000004,-0.000005,-0.000005,-0.000004,-0.000005,-0.000004,...,-8.378337e-07,-9.370473e-07,-1.042433e-08,-1.549445e-03,-1.897843e-03,-1.238018e-07,-8.322361e-10,-2.826360e-03,-1.617932e-08,-1.320345e-07
4.0,-0.000004,-0.000005,-0.000004,-0.000004,-0.000004,-0.000005,-0.000005,-0.000004,-0.000005,-0.000004,...,-8.338370e-07,-9.635269e-07,-1.182896e-09,-1.841977e-02,-1.763710e-02,-9.477465e-08,-2.779904e-10,-3.438173e-08,-1.541138e-08,-1.323165e-07

In [15]:
NaCurrCompSum.head()

gid           147760                                                    \
Section.ID       0         1         1         1         1         1
time
0.0         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
1.0        -0.000057 -0.003823 -0.003189 -0.002687 -0.002780 -0.002529
2.0        -0.000057 -0.003823 -0.003189 -0.002687 -0.002780 -0.002529
3.0        -0.000059 -0.003913 -0.003265 -0.002752 -0.002848 -0.002592
4.0        -0.000060 -0.003958 -0.003303 -0.002785 -0.002882 -0.002624

gid                                                 ... 163089                 \
Section.ID       2         2         2         2    ...    268  268  269  270
time                                                ...
0.0         0.000000  0.000000  0.000000  0.000000  ...    0.0  0.0  0.0  0.0
1.0        -0.002000 -0.001899 -0.001498 -0.001514  ...    0.0  0.0  0.0  0.0
2.0        -0.002000 -0.001899 -0.001498 -0.001514  ...    0.0  0.0  0.0  0.0
3.0        -0.002051 -0.001947 -0.001537 -0.001554  ...    0.0  0.0  0.0  0.0
4.0        -0.002077 -0.001973 -0.001558 -0.001576  ...    0.0  0.0  0.0  0.0

gid
Section.ID  271  271  271  272  272  272
time
0.0         0.0  0.0  0.0  0.0  0.0  0.0
1.0         0.0  0.0  0.0  0.0  0.0  0.0
2.0         0.0  0.0  0.0  0.0  0.0  0.0
3.0         0.0  0.0  0.0  0.0  0.0  0.0
4.0         0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 1561041 columns]

In [17]:
NaCurrCompSum[147760].sum(axis=1)

time
0.0      0.000000
1.0     -0.023570
2.0     -0.023570
3.0     -0.024151
4.0     -0.024451
5.0     -0.024588
6.0     -0.024522
7.0     -0.024532
8.0     -0.024448
9.0     -0.024330
10.0    -0.024241
11.0   -40.370903
12.0    -8.949965
13.0    -5.490816
14.0    -5.613426
15.0    -1.894217
16.0    -0.597193
17.0    -0.848392
18.0    -1.462304
19.0    -1.462304
20.0    -2.156601
21.0    -2.184923
22.0    -1.775555
23.0    -1.561443
24.0    -1.524374
25.0    -1.522783
26.0    -1.506038
27.0    -1.478736
28.0    -1.453122
29.0    -1.418607
30.0    -1.409420
31.0    -1.399726
32.0    -1.405690
33.0    -1.415238
34.0    -1.521330
35.0    -1.522844
36.0    -1.447478
37.0    -1.340318
38.0    -1.268584
39.0    -1.223490
40.0    -1.199122
41.0    -1.176054
42.0    -1.160921
43.0    -1.149752
44.0    -1.129722
45.0    -1.154018
46.0    -1.218954
47.0    -1.285397
48.0    -1.378017
49.0    -2.068090
dtype: float32

In [24]:
NaCurrCellSum[147826]-current_ina_nA[147826]

time
0.0     2.897759e-14
1.0    -2.897743e-02
2.0    -2.897743e-02
3.0    -2.935601e-02
4.0    -2.934522e-02
5.0    -2.900470e-02
6.0    -2.824314e-02
7.0    -2.730155e-02
8.0    -2.640894e-02
9.0    -2.577675e-02
10.0   -2.515906e-02
11.0   -3.393483e+01
12.0   -3.809870e+00
13.0   -2.039355e+00
14.0   -1.063749e+01
15.0   -2.239973e+00
16.0   -2.366463e-01
17.0   -1.468707e-01
18.0   -1.411027e-01
19.0   -1.411027e-01
20.0   -1.435847e-01
21.0   -1.497293e-01
22.0   -1.617642e-01
23.0   -1.748336e-01
24.0   -1.927604e-01
25.0   -2.189718e-01
26.0   -2.591981e-01
27.0   -3.259375e-01
28.0   -4.519376e-01
29.0   -8.296843e-01
30.0   -3.066003e+01
31.0   -2.869883e+00
32.0   -3.593248e-01
33.0   -9.326262e-02
34.0   -4.927126e-02
35.0   -3.469477e-02
36.0   -2.893674e-02
37.0   -2.661628e-02
38.0   -2.573627e-02
39.0   -2.526584e-02
40.0   -2.489553e-02
41.0   -2.403346e-02
42.0   -2.467493e-02
43.0   -2.548288e-02
44.0   -2.578519e-02
45.0   -2.535001e-02
46.0   -2.466008e-02
47.0   -2.390951e-02
48.0   -2.319141e-02
49.0   -2.250363e-02
Name: 147826, dtype: float64

In [25]:
NaCurrCellSum[147826]-current_ina_origin_noScaling[147826]

time
0.0      0.155417
1.0      0.128497
2.0      0.128458
3.0      0.127434
4.0      0.126270
5.0      0.122527
6.0      0.118222
7.0      0.114357
8.0      0.111851
9.0      0.109158
10.0    82.026204
11.0   -18.654189
12.0     2.561019
13.0    31.617405
14.0    -3.930324
15.0    -1.220077
16.0     0.451420
17.0     0.561952
18.0     0.594225
19.0     0.625989
20.0     0.677501
21.0     0.731395
22.0     0.802683
23.0     0.912504
24.0     1.084021
25.0     1.373027
26.0     1.932686
27.0     3.738499
28.0    43.910859
29.0    11.195130
30.0   -29.142058
31.0    -2.335128
32.0    -0.057735
33.0     0.112064
34.0     0.117974
35.0     0.117269
36.0     0.117188
37.0     0.116117
38.0     0.114100
39.0     0.109451
40.0     0.111944
41.0     0.115124
42.0     0.114067
43.0     0.109581
44.0     0.104811
45.0     0.100951
46.0     0.097889
47.0     0.095312
48.0     0.093181
49.0     0.090997
Name: 147826, dtype: float64

In [19]:
NaCurrSoma[147826]-current_ina_nA[147826]

time
0.0     2.897759e-14
1.0    -3.991495e-06
2.0    -4.064277e-06
3.0    -4.066570e-06
4.0    -4.046728e-06
5.0    -4.010249e-06
6.0    -3.864097e-06
7.0    -3.690054e-06
8.0    -3.527290e-06
9.0    -3.408671e-06
10.0   -3.296222e-06
11.0   -1.504089e+00
12.0   -5.246579e-03
13.0   -2.971611e-02
14.0   -4.421218e-01
15.0   -8.036421e-02
16.0   -4.929295e-05
17.0   -8.309913e-05
18.0   -1.274363e-04
19.0   -1.567261e-04
20.0   -1.777925e-04
21.0   -2.126005e-04
22.0   -2.415784e-04
23.0   -2.804144e-04
24.0   -3.384861e-04
25.0   -4.329631e-04
26.0   -6.031616e-04
27.0   -9.547724e-04
28.0   -2.033416e-03
29.0   -2.031371e+00
30.0   -1.723516e-02
31.0   -4.441762e-06
32.0   -2.649321e-06
33.0   -2.332541e-06
34.0   -2.207641e-06
35.0   -2.257156e-06
36.0   -2.434143e-06
37.0   -2.646660e-06
38.0   -2.823829e-06
39.0   -2.953531e-06
40.0   -2.819046e-06
41.0   -2.674638e-06
42.0   -2.772729e-06
43.0   -2.928565e-06
44.0   -2.985580e-06
45.0   -3.024780e-06
46.0   -3.013421e-06
47.0   -2.982131e-06
48.0   -2.935223e-06
49.0   -2.900714e-06
Name: 147826, dtype: float64

In [20]:
NaCurrSoma[147826]-current_ina_origin_noScaling[147826]

time
0.0      0.155417
1.0      0.157471
2.0      0.157432
3.0      0.156786
4.0      0.155611
5.0      0.151527
6.0      0.146461
7.0      0.141654
8.0      0.138256
9.0      0.134931
10.0    82.051360
11.0    13.776552
12.0     6.365642
13.0    33.627044
14.0     6.265044
15.0     0.939532
16.0     0.688017
17.0     0.708739
18.0     0.735201
19.0     0.766935
20.0     0.820908
21.0     0.880912
22.0     0.964206
23.0     1.087057
24.0     1.276442
25.0     1.591566
26.0     2.191281
27.0     4.063482
28.0    44.360763
29.0     9.993443
30.0     1.500735
31.0     0.534751
32.0     0.301587
33.0     0.205324
34.0     0.167243
35.0     0.151961
36.0     0.146123
37.0     0.142731
38.0     0.139833
39.0     0.134714
40.0     0.136837
41.0     0.139155
42.0     0.138739
43.0     0.135061
44.0     0.130593
45.0     0.126298
46.0     0.122546
47.0     0.119219
48.0     0.116370
49.0     0.113498
Name: 147826, dtype: float64

In [23]:
NaCurrCompSum[147826].sum(axis=1)-current_ina_nA[147826]

time
0.0     2.897759e-14
1.0    -2.897743e-02
2.0    -2.897743e-02
3.0    -2.935600e-02
4.0    -2.934522e-02
5.0    -2.900470e-02
6.0    -2.824314e-02
7.0    -2.730155e-02
8.0    -2.640894e-02
9.0    -2.577675e-02
10.0   -2.515906e-02
11.0   -3.393483e+01
12.0   -3.809870e+00
13.0   -2.039355e+00
14.0   -1.063749e+01
15.0   -2.239973e+00
16.0   -2.366463e-01
17.0   -1.468707e-01
18.0   -1.411027e-01
19.0   -1.411027e-01
20.0   -1.435847e-01
21.0   -1.497293e-01
22.0   -1.617643e-01
23.0   -1.748336e-01
24.0   -1.927604e-01
25.0   -2.189718e-01
26.0   -2.591981e-01
27.0   -3.259375e-01
28.0   -4.519377e-01
29.0   -8.296843e-01
30.0   -3.066003e+01
31.0   -2.869883e+00
32.0   -3.593248e-01
33.0   -9.326262e-02
34.0   -4.927126e-02
35.0   -3.469477e-02
36.0   -2.893674e-02
37.0   -2.661628e-02
38.0   -2.573627e-02
39.0   -2.526584e-02
40.0   -2.489553e-02
41.0   -2.403346e-02
42.0   -2.467493e-02
43.0   -2.548288e-02
44.0   -2.578519e-02
45.0   -2.535001e-02
46.0   -2.466008e-02
47.0   -2.390951e-02
48.0   -2.319141e-02
49.0   -2.250363e-02
dtype: float64

In [22]:
NaCurrCompSum[147826].sum(axis=1)-current_ina_origin_noScaling[147826]

time
0.0      0.155417
1.0      0.128497
2.0      0.128458
3.0      0.127434
4.0      0.126270
5.0      0.122527
6.0      0.118222
7.0      0.114357
8.0      0.111851
9.0      0.109158
10.0    82.026204
11.0   -18.654189
12.0     2.561019
13.0    31.617405
14.0    -3.930323
15.0    -1.220077
16.0     0.451420
17.0     0.561952
18.0     0.594225
19.0     0.625989
20.0     0.677501
21.0     0.731395
22.0     0.802683
23.0     0.912504
24.0     1.084021
25.0     1.373027
26.0     1.932686
27.0     3.738499
28.0    43.910859
29.0    11.195130
30.0   -29.142058
31.0    -2.335128
32.0    -0.057735
33.0     0.112064
34.0     0.117974
35.0     0.117269
36.0     0.117188
37.0     0.116117
38.0     0.114100
39.0     0.109451
40.0     0.111944
41.0     0.115124
42.0     0.114067
43.0     0.109581
44.0     0.104811
45.0     0.100951
46.0     0.097889
47.0     0.095312
48.0     0.093181
49.0     0.090997
dtype: float64