In [26]:
!pwd

/gpfs/bbp.cscs.ch/project/proj34/metabolismndam/analysis/sim_analyze

In [1]:
import efel

from bluepy.v2 import Simulation

from bluepy.v2 import Circuit
from bluepy.v2 import Cell
from bluepy.v2.enums import Synapse

from os import path

import pandas as pd

import numpy as np

from matplotlib import pyplot as plt
import seaborn as sns

import h5py

import pickle

In [2]:
sim_f = '/gpfs/bbp.cscs.ch/project/proj34/sh_ngvm/column/ina_new_jorge/BlueConfig'

sim = Simulation(sim_f)

Have keys ({'FlushBufferScalar'}) that are not defined for section: Run

In [3]:
report = sim.report('NaCurrCellSum', source='h5') # NaCurrCellSum
NaCurrCellSum = report.get()
print("NUMBER OF COLUMNS:",len(NaCurrCellSum.columns))

Ignoring unknown key: 'FlushBufferScalar'

NUMBER OF COLUMNS: 2132

In [4]:
report = sim.report('NaCurrCellSumNosc', source='h5') # NaCurrCellSum
NaCurrCellSumNosc = report.get()
print("NUMBER OF COLUMNS:",len(NaCurrCellSumNosc.columns))

Ignoring unknown key: 'FlushBufferScalar'

NUMBER OF COLUMNS: 2132

In [5]:
# from iter seg in py
param = pd.read_csv('/gpfs/bbp.cscs.ch/project/proj34/sh_ngvm/column/ina_new_jorge/param_2020122315.txt',sep='\t',header=None)

param.columns = ['c_gid','rank','idxm','current_ina_nA','current_ina_origin_noScaling','nais_mean']
param['c_gid'] = param['c_gid'].astype(int)
param['idxm'] = param['idxm'].astype(float)

In [6]:
param.head()

    c_gid  rank  idxm  current_ina_nA  current_ina_origin_noScaling  nais_mean
0  156313  1193   0.0       -0.031385                     -0.117971       10.0
1  156233  1185   0.0       -0.032149                     -0.107216       10.0
2  156366  1198   0.0       -0.041161                     -0.112710       10.0
3  156208  1180   0.0       -0.031584                     -0.111386       10.0
4  156223  1184   0.0       -0.040878                     -0.119770       10.0

In [8]:
# check that all mpi ranks output data
len(param['rank'].unique())

1024

In [7]:
current_ina_nA = param.pivot(index='idxm', columns='c_gid', values='current_ina_nA')

In [8]:
current_ina_origin_noScaling = param.pivot(index='idxm', columns='c_gid', values='current_ina_origin_noScaling')

In [9]:
current_ina_nA.head()

c_gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
idxm,,,,,,,,,,,,,,,,,,,,,
0.0,-0.023570,-0.036212,-0.038118,-0.047140,-0.030195,-0.035057,-0.025436,-0.038473,-0.031252,-0.028978,...,-0.012469,-0.037754,-0.107033,-0.040726,-0.040896,-0.031467,-5.642699,-0.071667,-0.014953,-0.035600
1.0,-0.024151,-0.037415,-0.039115,-0.047964,-0.030629,-0.036488,-0.026680,-0.039007,-0.033469,-0.029356,...,-0.012482,-0.040979,-10.559535,-0.065654,-0.066201,-0.032970,-0.416624,-16.674305,-0.014854,-0.036541
2.0,-0.024451,-0.037929,-0.039522,-0.048059,-0.030375,-0.037058,-0.027338,-0.039067,-0.034475,-0.029345,...,-0.012490,-0.041898,-0.000071,-8.128112,-8.109960,-0.031682,-0.000108,-0.059622,-0.014506,-0.036674
3.0,-0.024565,-0.038202,-0.039595,-0.047889,-0.030137,-0.037302,-0.027354,-0.038770,-0.034811,-0.029223,...,-0.012420,-0.042284,-0.000044,-0.613222,-0.592900,-0.024450,-0.000101,-0.000311,-0.013966,-0.036627
4.0,-0.024588,-0.038492,-0.039514,-0.047532,-0.029893,-0.037482,-0.026366,-0.038431,-0.034479,-0.029005,...,-0.012371,-0.042696,-0.000060,-0.011459,-0.011256,-0.019044,-0.000146,-0.000337,-0.013487,-0.036071

In [10]:
current_ina_origin_noScaling.head()

c_gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
idxm,,,,,,,,,,,,,,,,,,,,,
0.0,-0.114722,-0.113925,-0.114402,-0.107158,-0.106662,-0.110488,-0.115624,-0.105044,-0.113717,-0.111107,...,-0.142126,-0.346648,-1.326097,-0.329266,-0.330671,-0.250399,-62.805036,-0.575969,-0.123093,-0.229509
1.0,-0.117585,-0.117757,-0.117413,-0.109043,-0.108193,-0.115051,-0.121377,-0.106517,-0.121776,-0.112577,...,-0.142214,-0.378480,-29.503419,-0.534913,-0.539477,-0.262835,-3.351076,-64.433259,-0.122299,-0.235628
2.0,-0.119087,-0.119401,-0.118647,-0.109264,-0.107295,-0.116874,-0.124446,-0.106686,-0.125433,-0.112548,...,-0.142243,-0.387050,-0.000663,-62.222928,-61.984297,-0.252570,-0.001018,-0.225235,-0.119438,-0.236372
3.0,-0.119663,-0.120272,-0.118869,-0.108880,-0.106457,-0.117658,-0.124581,-0.105880,-0.126651,-0.112085,...,-0.141422,-0.390090,-0.000449,-3.137211,-3.039219,-0.193141,-0.001019,-0.002196,-0.114954,-0.235961
4.0,-0.119788,-0.121196,-0.118631,-0.108072,-0.105594,-0.118232,-0.120026,-0.104956,-0.125444,-0.111244,...,-0.140833,-0.393706,-0.000623,-0.077068,-0.075745,-0.149412,-0.001525,-0.002447,-0.111009,-0.232187

In [11]:
NaCurrCellSum.head()

gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
time,,,,,,,,,,,,,,,,,,,,,
0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1.0,-0.023570,-0.036212,-0.038118,-0.047140,-0.030195,-0.035057,-0.025436,-0.038473,-0.031252,-0.028977,...,-0.012469,-0.037754,-0.107033,-0.040726,-0.040896,-0.031467,-5.642692,-0.071667,-0.014953,-0.035600
2.0,-0.023570,-0.036212,-0.038118,-0.047140,-0.030195,-0.035057,-0.025436,-0.038473,-0.031252,-0.028977,...,-0.012469,-0.037754,-0.107033,-0.040726,-0.040896,-0.031467,-5.642692,-0.071667,-0.014953,-0.035600
3.0,-0.024151,-0.037415,-0.039115,-0.047964,-0.030629,-0.036488,-0.026680,-0.039007,-0.033469,-0.029356,...,-0.012482,-0.040979,-10.559533,-0.065654,-0.066201,-0.032970,-0.416624,-16.674309,-0.014854,-0.036541
4.0,-0.024451,-0.037929,-0.039522,-0.048059,-0.030375,-0.037058,-0.027338,-0.039067,-0.034475,-0.029345,...,-0.012490,-0.041898,-0.000071,-8.128112,-8.109953,-0.031682,-0.000108,-0.059622,-0.014506,-0.036674

In [12]:
NaCurrCellSumNosc.head()

gid,147760,147761,147789,147792,147794,147796,147811,147813,147824,147826,...,162976,163006,163022,163027,163031,163038,163046,163050,163064,163089
time,,,,,,,,,,,,,,,,,,,,,
0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1.0,-0.114722,-0.113925,-0.114402,-0.107158,-0.106662,-0.110488,-0.115624,-0.105044,-0.113717,-0.111107,...,-0.142126,-0.346648,-1.326097,-0.329266,-0.330671,-0.250399,-62.805035,-0.575969,-0.123093,-0.229509
2.0,-0.114722,-0.113925,-0.114402,-0.107158,-0.106662,-0.110488,-0.115624,-0.105044,-0.113717,-0.111107,...,-0.142126,-0.346648,-1.326097,-0.329266,-0.330671,-0.250399,-62.805035,-0.575969,-0.123093,-0.229509
3.0,-0.117585,-0.117757,-0.117413,-0.109043,-0.108193,-0.115051,-0.121377,-0.106517,-0.121776,-0.112577,...,-0.142214,-0.378480,-29.503420,-0.534913,-0.539477,-0.262835,-3.351076,-64.433258,-0.122299,-0.235628
4.0,-0.119087,-0.119401,-0.118647,-0.109264,-0.107295,-0.116874,-0.124446,-0.106686,-0.125433,-0.112547,...,-0.142243,-0.387050,-0.000663,-62.222927,-61.984295,-0.252570,-0.001018,-0.225235,-0.119438,-0.236372

In [22]:
NaCurrCellSumNosc = NaCurrCellSumNosc.iloc[1:len(NaCurrCellSumNosc),:]

In [25]:
NaCurrCellSumNosc = NaCurrCellSumNosc.reset_index()

In [23]:
len(NaCurrCellSumNosc)

49

In [29]:
current_ina_origin_noScaling = current_ina_origin_noScaling.reset_index()

In [31]:
NaCurrCellSumNosc[147826].values-current_ina_origin_noScaling[147826][1:50].values

array([ 1.47007294e-03,  1.44043684e-03, -4.92175802e-04, -1.30343882e-03,
       -2.92073027e-03, -3.62289733e-03, -3.43710628e-03, -2.42991783e-03,
       -2.37750094e-03,  5.16754680e+01, -4.01984617e+01, -6.98710942e+00,
        1.87503080e+01, -1.85928695e+01, -3.93424135e+00, -2.03793430e-01,
        2.89523063e-02,  2.51379964e-02,  5.26514613e-02,  6.61220605e-02,
        8.11676330e-02,  1.01494856e-01,  1.45581298e-01,  2.20548338e-01,
        3.57127597e-01,  6.49926990e-01,  1.76438894e+00,  2.54562811e+01,
        5.09669049e+00, -2.59131131e+01, -7.56018030e+00, -8.77224506e-01,
       -2.54221512e-01, -1.04533436e-01, -4.40060487e-02, -1.92734223e-02,
       -9.85260548e-03, -7.12171235e-03, -7.86679412e-03, -2.44114790e-03,
        4.56223819e-03,  2.40463064e-03, -2.85928917e-03, -6.69595492e-03,
       -7.60498747e-03, -7.27541822e-03, -6.70455435e-03, -6.16292838e-03,
       -5.92969924e-03])

In [18]:
NaCurrCellSum[147826]-current_ina_origin_noScaling[147826]

time
0.0      0.111107
1.0      0.083600
2.0      0.083570
3.0      0.082729
4.0      0.081899
5.0      0.079318
6.0      0.076457
7.0      0.073961
8.0      0.072424
9.0      0.070679
10.0    51.746764
11.0   -22.498583
12.0     0.659456
13.0    21.181930
14.0    -6.009323
15.0    -1.546265
16.0     0.252730
17.0     0.371235
18.0     0.401990
19.0     0.429503
20.0     0.465515
21.0     0.501956
22.0     0.548756
23.0     0.622368
24.0     0.738248
25.0     0.935299
26.0     1.321677
27.0     2.592654
28.0    26.585137
29.0     7.185485
30.0   -29.536553
31.0    -2.440834
32.0    -0.110574
33.0     0.081661
34.0     0.094951
35.0     0.096223
36.0     0.096012
37.0     0.094448
38.0     0.092090
39.0     0.087932
40.0     0.090489
41.0     0.093726
42.0     0.093114
43.0     0.089417
44.0     0.085308
45.0     0.081944
46.0     0.079157
47.0     0.076680
48.0     0.074462
49.0     0.072156
Name: 147826, dtype: float64